Update CI workflow to install dependencies from requirements.txt, improve RUN_ID handling, and build Docker model with artifact path validation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,12 +18,12 @@ jobs:
 
       - name: Install dependencies
         run: |
-          pip install mlflow
+          pip install -r MLProject/requirements.txt
           # echo "MLFLOW_TRACKING_URI=${{ vars.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV
           echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}" >> $GITHUB_ENV
           echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV
-
       - name: Run MLflow Project and Capture RUN_ID
+        id: run_mlflow
         run: |
           cd MLProject
           mlflow run . --env-manager=local 2>&1 | tee output.log
@@ -36,17 +36,39 @@ jobs:
           
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           echo "Validated RUN_ID: $RUN_ID"
-
-      - name: Upload ML artifact to GitHub
+      - name: Upload ML artifact
         uses: actions/upload-artifact@v4
         with:
-          name: artifacts
+          name: artifact
           path: MLProject
 
       - name: Build Docker Model
         run: |
-          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "hiring_prediction_model"
-
+          MODEL_PATH="MLProject/mlruns/0/${{ env.RUN_ID }}/artifacts/model"
+          
+          if [ ! -d "$MODEL_PATH" ]; then
+            echo "Model artifacts not found at $MODEL_PATH"
+            exit 1
+          fi
+          mlflow models build-docker \
+            --model-uri "$MODEL_PATH" \
+            --name "hiring_prediction_model"\
+      # - name: Build Docker Model
+      #   run: |
+      #     echo "Using RUN_ID: ${{ env.RUN_ID }}"
+      #     export MLFLOW_TRACKING_URI=./MLProject/mlruns
+          
+      #     # Generate Dockerfile first
+      #     mlflow models generate-dockerfile \
+      #       --model-uri "runs:/${{ env.RUN_ID }}/model" \
+      #       --output-file Dockerfile
+            
+      #     # Modify Dockerfile to bind to 0.0.0.0
+      #     sed -i 's|CMD \["mlflow", "models", "serve"|CMD \["mlflow", "models", "serve", "--host", "0.0.0.0"|' Dockerfile
+          
+      #     # Build the image
+      #     docker build -t hiring_prediction_model -f Dockerfile .
+          
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
